Leadership Change
TriangleDevOps/policies pull request #2
Opened 2017-03-13 19:42 UTC by chris-short

Changes to policies where required due to change in co-organizers.

2017-03-15 20:19 UTC, base10 requested changes
I have two small change requests, please.

2017-03-15 20:19 UTC, base10 commented on code-of-conduct.md
> -[add-rec]: additional-resources.md
I saw this was a dead link, but could you 1) retain the link and 2) update this to conduct-resources.md? Thanks

2017-03-15 20:19 UTC, base10 commented on README.md
> +* Chris Bailey
If Chris Bailey is on the hot list to be contacted, can we get contact information here for him?

2017-03-16 16:15 UTC, chris-short commented
All requests fulfilled

2017-03-16 16:16 UTC, merged